import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'
import BaseContainer from '@/components/base.container'
import Providers from '@/utils/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <BaseContainer>
            {children}
          </BaseContainer>
        </Providers>
      </body>
    </html>
  )
}
